from __future__ import annotations

from collections.abc import Sequence
from copy import deepcopy
from typing import Any


CONTEXT_FIELDS: dict[str, dict[str, Any]] = {
    "country_risk": {
        "key": "country_risk",
        "label": "Риск страны",
        "kind": "select",
        "default": "low",
        "help": "Учебная оценка юрисдикции, связанной с операцией.",
        "options": [
            {"value": "low", "label": "Низкий"},
            {"value": "medium", "label": "Средний"},
            {"value": "high", "label": "Высокий"},
        ],
    },
    "recipient_type": {
        "key": "recipient_type",
        "label": "Получатель",
        "kind": "select",
        "default": "known_counterparty",
        "help": "Насколько хорошо клиенту известна принимающая сторона.",
        "options": [
            {"value": "known_counterparty", "label": "Знакомый контрагент"},
            {"value": "new_counterparty", "label": "Новый контрагент"},
            {"value": "anonymous_wallet", "label": "Анонимный кошелек"},
        ],
    },
    "time_of_day": {
        "key": "time_of_day",
        "label": "Время операции",
        "kind": "select",
        "default": "day",
        "help": "Нетипичное время может усилить сигнал модели.",
        "options": [
            {"value": "day", "label": "День"},
            {"value": "evening", "label": "Вечер"},
            {"value": "night", "label": "Ночь"},
        ],
    },
    "velocity": {
        "key": "velocity",
        "label": "Темп повторов",
        "kind": "select",
        "default": "normal",
        "help": "Интервал между повторами внутри одного шага.",
        "options": [
            {"value": "spaced", "label": "С интервалами"},
            {"value": "normal", "label": "Обычный темп"},
            {"value": "rapid", "label": "Быстро подряд"},
        ],
    },
    "has_documents": {
        "key": "has_documents",
        "label": "Есть подтверждающие документы",
        "kind": "toggle",
        "default": True,
        "help": "Документы требуют времени, но снижают неопределенность модели.",
    },
}


ACTION_CONTEXT_FIELDS: dict[str, tuple[str, ...]] = {
    "salary": ("time_of_day", "has_documents"),
    "cash_deposit": ("time_of_day", "velocity", "has_documents"),
    "card_transfer": (
        "recipient_type",
        "time_of_day",
        "velocity",
        "has_documents",
    ),
    "international": (
        "country_risk",
        "recipient_type",
        "time_of_day",
        "velocity",
        "has_documents",
    ),
    "cash_withdrawal": ("time_of_day", "velocity"),
    "crypto_exchange": ("country_risk", "time_of_day", "velocity", "has_documents"),
    "online_purchase": ("country_risk", "time_of_day", "velocity"),
    "refund": ("time_of_day", "velocity", "has_documents"),
}


ACTION_PARAMETER_SCHEMAS: dict[str,
                               tuple[dict[str,
                                          Any],
                                     ...]] = {"salary": ({"key": "employer_profile",
                                                          "label": "Плательщик",
                                                          "kind": "select",
                                                          "default": "verified_employer",
                                                          "help": "Профиль отправителя регулярного дохода.",
                                                          "options": [{"value": "verified_employer",
                                                                       "label": "Проверенный работодатель",
                                                                       "risk_points": -5,
                                                                       "trust_cost": -2,
                                                                       "description": "Известный работодатель снижает неопределенность дохода",
                                                                       },
                                                                      {"value": "small_business",
                                                                       "label": "Малый бизнес",
                                                                       "risk_points": 1,
                                                                       "trust_cost": 1,
                                                                       "description": "Небольшой работодатель дает модели меньше истории",
                                                                       },
                                                                      {"value": "private_person",
                                                                       "label": "Физическое лицо",
                                                                       "risk_points": 8,
                                                                       "trust_cost": 6,
                                                                       "energy_cost": 1,
                                                                       "description": "Перевод от физлица слабее похож на зарплатную выплату",
                                                                       },
                                                                      ],
                                                          },
                                                         {"key": "income_basis",
                                                          "label": "Основание дохода",
                                                          "kind": "select",
                                                          "default": "payroll_registry",
                                                          "options": [{"value": "payroll_registry",
                                                                       "label": "Зарплатный реестр",
                                                                       "risk_points": -3,
                                                                       "trust_cost": -1,
                                                                       "time_cost": 1,
                                                                       "description": "Назначение и реестр подтверждают регулярность выплаты",
                                                                       },
                                                                      {"value": "service_contract",
                                                                       "label": "Договор услуг",
                                                                       "risk_points": 2,
                                                                       "trust_cost": 2,
                                                                       "description": "Нерегулярный договор требует дополнительного контекста",
                                                                       },
                                                                      {"value": "no_reference",
                                                                       "label": "Без назначения",
                                                                       "risk_points": 8,
                                                                       "trust_cost": 6,
                                                                       "description": "Отсутствие назначения затрудняет проверку источника дохода",
                                                                       },
                                                                      ],
                                                          },
                                                         ),
                                              "cash_deposit": ({"key": "funds_source",
                                                                "label": "Источник наличных",
                                                                "kind": "select",
                                                                "default": "documented_savings",
                                                                "options": [{"value": "documented_savings",
                                                                             "label": "Подтвержденные накопления",
                                                                             "risk_points": -2,
                                                                             "trust_cost": -2,
                                                                             "time_cost": 1,
                                                                             "description": "Понятный источник средств снижает неопределенность",
                                                                             },
                                                                            {"value": "asset_sale",
                                                                             "label": "Продажа имущества",
                                                                             "risk_points": 2,
                                                                             "trust_cost": 1,
                                                                             "time_cost": 1,
                                                                             "description": "Разовое поступление требует подтверждения сделки",
                                                                             },
                                                                            {"value": "borrowed_cash",
                                                                             "label": "Заемные средства",
                                                                             "risk_points": 5,
                                                                             "trust_cost": 4,
                                                                             "description": "Заемные наличные сложнее связать с финансовым профилем",
                                                                             },
                                                                            {"value": "unexplained",
                                                                             "label": "Источник не указан",
                                                                             "risk_points": 12,
                                                                             "trust_cost": 10,
                                                                             "energy_cost": 1,
                                                                             "description": "Необъясненные наличные дают сильный сигнал риска",
                                                                             },
                                                                            ],
                                                                },
                                                               {"key": "deposit_pattern",
                                                                "label": "Способ внесения",
                                                                "kind": "select",
                                                                "default": "single_location",
                                                                "options": [{"value": "single_location",
                                                                             "label": "Одно место",
                                                                             "risk_points": -1,
                                                                             "trust_cost": -1,
                                                                             "description": "Обычное внесение в одном месте выглядит последовательнее",
                                                                             },
                                                                            {"value": "several_atms",
                                                                             "label": "Несколько банкоматов",
                                                                             "risk_points": 6,
                                                                             "trust_cost": 5,
                                                                             "energy_cost": 1,
                                                                             "description": "Разные точки внесения похожи на распределенную схему",
                                                                             },
                                                                            {"value": "third_party",
                                                                             "label": "Через третье лицо",
                                                                             "risk_points": 10,
                                                                             "trust_cost": 8,
                                                                             "description": "Внесение третьим лицом усложняет установление источника",
                                                                             },
                                                                            ],
                                                                },
                                                               ),
                                              "card_transfer": ({"key": "transfer_purpose",
                                                                 "label": "Назначение перевода",
                                                                 "kind": "select",
                                                                 "default": "family_support",
                                                                 "options": [{"value": "family_support",
                                                                              "label": "Помощь семье",
                                                                              "risk_points": -2,
                                                                              "trust_cost": -1,
                                                                              "description": "Понятное бытовое назначение соответствует профилю клиента",
                                                                              },
                                                                             {"value": "goods_payment",
                                                                              "label": "Оплата товара",
                                                                              "risk_points": 1,
                                                                              "description": "Перевод вместо эквайринга требует контекста сделки",
                                                                              },
                                                                             {"value": "loan_repayment",
                                                                              "label": "Возврат долга",
                                                                              "risk_points": 2,
                                                                              "trust_cost": 1,
                                                                              "description": "Возврат долга труднее подтвердить автоматически",
                                                                              },
                                                                             {"value": "no_purpose",
                                                                              "label": "Без назначения",
                                                                              "risk_points": 6,
                                                                              "trust_cost": 4,
                                                                              "description": "Пустое назначение повышает неопределенность перевода",
                                                                              },
                                                                             ],
                                                                 },
                                                                {"key": "recipient_relationship",
                                                                 "label": "Связь с получателем",
                                                                 "kind": "select",
                                                                 "default": "family",
                                                                 "options": [{"value": "own_account",
                                                                              "label": "Собственный счет",
                                                                              "risk_points": -4,
                                                                              "trust_cost": -2,
                                                                              "description": "Перевод между собственными счетами хорошо объясним",
                                                                              },
                                                                             {"value": "family",
                                                                              "label": "Родственник",
                                                                              "risk_points": -2,
                                                                              "description": "Устойчивая связь с получателем снижает неопределенность",
                                                                              },
                                                                             {"value": "acquaintance",
                                                                              "label": "Знакомый",
                                                                              "risk_points": 2,
                                                                              "trust_cost": 2,
                                                                              "description": "Неформальная связь требует больше контекста",
                                                                              },
                                                                             {"value": "unknown",
                                                                              "label": "Связь не указана",
                                                                              "risk_points": 8,
                                                                              "trust_cost": 6,
                                                                              "description": "Неясная связь с получателем усиливает риск",
                                                                              },
                                                                             ],
                                                                 },
                                                                ),
                                              "international": ({"key": "transfer_purpose",
                                                                 "label": "Назначение перевода",
                                                                 "kind": "select",
                                                                 "default": "tuition",
                                                                 "options": [{"value": "tuition",
                                                                              "label": "Обучение",
                                                                              "risk_points": -4,
                                                                              "trust_cost": -2,
                                                                              "time_cost": 1,
                                                                              "description": "Платеж образовательной организации хорошо документируется",
                                                                              },
                                                                             {"value": "family_support",
                                                                              "label": "Поддержка семьи",
                                                                              "risk_points": 0,
                                                                              "description": "Личный перевод требует проверки связи с получателем",
                                                                              },
                                                                             {"value": "invoice",
                                                                              "label": "Оплата счета",
                                                                              "risk_points": 2,
                                                                              "trust_cost": 1,
                                                                              "time_cost": 1,
                                                                              "description": "Коммерческий счет требует проверки контрагента",
                                                                              },
                                                                             {"value": "investment",
                                                                              "label": "Инвестиции",
                                                                              "risk_points": 6,
                                                                              "trust_cost": 4,
                                                                              "description": "Инвестиционный перевод имеет более сложный экономический смысл",
                                                                              },
                                                                             ],
                                                                 },
                                                                {"key": "payment_route",
                                                                 "label": "Маршрут платежа",
                                                                 "kind": "select",
                                                                 "default": "named_bank",
                                                                 "options": [{"value": "named_bank",
                                                                              "label": "Банк получателя",
                                                                              "risk_points": -2,
                                                                              "trust_cost": -1,
                                                                              "time_cost": 1,
                                                                              "description": "Прямой банковский маршрут проще проверить",
                                                                              },
                                                                             {"value": "correspondent_chain",
                                                                              "label": "Цепочка корреспондентов",
                                                                              "risk_points": 3,
                                                                              "trust_cost": 2,
                                                                              "description": "Несколько банков увеличивают сложность маршрута",
                                                                              },
                                                                             {"value": "fintech_gateway",
                                                                              "label": "Финтех-посредник",
                                                                              "risk_points": 6,
                                                                              "trust_cost": 4,
                                                                              "energy_cost": 1,
                                                                              "description": "Посредник сокращает прозрачность конечного маршрута",
                                                                              },
                                                                             ],
                                                                 },
                                                                ),
                                              "cash_withdrawal": ({"key": "cash_purpose",
                                                                   "label": "Назначение наличных",
                                                                   "kind": "select",
                                                                   "default": "daily_expenses",
                                                                   "options": [{"value": "daily_expenses",
                                                                                "label": "Повседневные расходы",
                                                                                "risk_points": -2,
                                                                                "trust_cost": -1,
                                                                                "description": "Обычное назначение соответствует розничному профилю",
                                                                                },
                                                                               {"value": "major_purchase",
                                                                                "label": "Крупная покупка",
                                                                                "risk_points": 1,
                                                                                "description": "Крупная покупка наличными требует объяснения",
                                                                                },
                                                                               {"value": "business_expenses",
                                                                                "label": "Расходы бизнеса",
                                                                                "risk_points": 3,
                                                                                "trust_cost": 2,
                                                                                "description": "Бизнес-расходы не всегда соответствуют личному профилю",
                                                                                },
                                                                               {"value": "unspecified",
                                                                                "label": "Не указано",
                                                                                "risk_points": 7,
                                                                                "trust_cost": 6,
                                                                                "description": "Неясная цель снятия усиливает риск вывода средств",
                                                                                },
                                                                               ],
                                                                   },
                                                                  {"key": "withdrawal_location",
                                                                   "label": "Место снятия",
                                                                   "kind": "select",
                                                                   "default": "home_region",
                                                                   "options": [{"value": "home_region",
                                                                                "label": "Домашний регион",
                                                                                "risk_points": -2,
                                                                                "trust_cost": -1,
                                                                                "description": "Привычная география соответствует профилю клиента",
                                                                                },
                                                                               {"value": "other_region",
                                                                                "label": "Другой регион",
                                                                                "risk_points": 3,
                                                                                "trust_cost": 3,
                                                                                "description": "Новая география требует дополнительного контекста",
                                                                                },
                                                                               {"value": "abroad",
                                                                                "label": "За границей",
                                                                                "risk_points": 7,
                                                                                "trust_cost": 6,
                                                                                "energy_cost": 1,
                                                                                "description": "Снятие за границей заметно отличается от обычного поведения",
                                                                                },
                                                                               ],
                                                                   },
                                                                  ),
                                              "crypto_exchange": ({"key": "platform_profile",
                                                                   "label": "Тип площадки",
                                                                   "kind": "select",
                                                                   "default": "licensed_exchange",
                                                                   "options": [{"value": "licensed_exchange",
                                                                                "label": "Лицензированная биржа",
                                                                                "risk_points": -4,
                                                                                "trust_cost": -3,
                                                                                "time_cost": 1,
                                                                                "description": "Идентифицированная площадка дает больше проверяемых данных",
                                                                                },
                                                                               {"value": "p2p_market",
                                                                                "label": "P2P-площадка",
                                                                                "risk_points": 6,
                                                                                "trust_cost": 6,
                                                                                "energy_cost": 1,
                                                                                "description": "P2P-сделка связывает клиента с частным контрагентом",
                                                                                },
                                                                               {"value": "unknown_service",
                                                                                "label": "Неизвестный сервис",
                                                                                "risk_points": 10,
                                                                                "trust_cost": 10,
                                                                                "energy_cost": 1,
                                                                                "description": "Неизвестный сервис дает минимум проверяемого контекста",
                                                                                },
                                                                               ],
                                                                   },
                                                                  {"key": "wallet_owner",
                                                                   "label": "Владелец кошелька",
                                                                   "kind": "select",
                                                                   "default": "own_wallet",
                                                                   "options": [{"value": "own_wallet",
                                                                                "label": "Собственный кошелек",
                                                                                "risk_points": -3,
                                                                                "trust_cost": -2,
                                                                                "description": "Собственный идентифицированный кошелек понятнее модели",
                                                                                },
                                                                               {"value": "relative_wallet",
                                                                                "label": "Кошелек родственника",
                                                                                "risk_points": 3,
                                                                                "trust_cost": 3,
                                                                                "description": "Чужой кошелек требует подтверждения связи",
                                                                                },
                                                                               {"value": "third_party_wallet",
                                                                                "label": "Кошелек третьего лица",
                                                                                "risk_points": 8,
                                                                                "trust_cost": 8,
                                                                                "description": "Перевод на кошелек третьего лица непрозрачен",
                                                                                },
                                                                               ],
                                                                   },
                                                                  {"key": "asset_profile",
                                                                   "label": "Тип актива",
                                                                   "kind": "select",
                                                                   "default": "major_asset",
                                                                   "options": [{"value": "major_asset",
                                                                                "label": "Крупный рыночный актив",
                                                                                "risk_points": 0,
                                                                                "description": "Распространенный актив не дает отдельного сигнала",
                                                                                },
                                                                               {"value": "stablecoin",
                                                                                "label": "Стейблкоин",
                                                                                "risk_points": 2,
                                                                                "trust_cost": 1,
                                                                                "description": ("Стейблкоины часто используются для быстрого перемещения стоимости"),
                                                                                },
                                                                               {"value": "privacy_asset",
                                                                                "label": "Анонимизирующий актив",
                                                                                "risk_points": 10,
                                                                                "trust_cost": 8,
                                                                                "energy_cost": 1,
                                                                                "description": "Анонимизирующий актив затрудняет анализ дальнейшего движения",
                                                                                },
                                                                               ],
                                                                   },
                                                                  ),
                                              "online_purchase": ({"key": "merchant_profile",
                                                                   "label": "Тип продавца",
                                                                   "kind": "select",
                                                                   "default": "known_marketplace",
                                                                   "options": [{"value": "known_marketplace",
                                                                                "label": "Известный маркетплейс",
                                                                                "risk_points": -3,
                                                                                "trust_cost": -2,
                                                                                "description": "У известной площадки есть история и понятный профиль",
                                                                                },
                                                                               {"value": "verified_store",
                                                                                "label": "Проверенный магазин",
                                                                                "risk_points": -1,
                                                                                "trust_cost": -1,
                                                                                "description": "Проверенный продавец снижает неопределенность покупки",
                                                                                },
                                                                               {"value": "new_store",
                                                                                "label": "Новый магазин",
                                                                                "risk_points": 3,
                                                                                "trust_cost": 2,
                                                                                "description": "У нового продавца мало истории операций",
                                                                                },
                                                                               {"value": "digital_goods",
                                                                                "label": "Цифровые товары",
                                                                                "risk_points": 5,
                                                                                "trust_cost": 4,
                                                                                "description": "Цифровой товар сложнее связать с физической поставкой",
                                                                                },
                                                                               ],
                                                                   },
                                                                  {"key": "delivery_match",
                                                                   "label": "Получение товара",
                                                                   "kind": "select",
                                                                   "default": "registered_address",
                                                                   "options": [{"value": "registered_address",
                                                                                "label": "Знакомый адрес",
                                                                                "risk_points": -3,
                                                                                "trust_cost": -2,
                                                                                "description": "Привычный адрес соответствует профилю клиента",
                                                                                },
                                                                               {"value": "pickup_point",
                                                                                "label": "Пункт выдачи",
                                                                                "risk_points": 0,
                                                                                "description": "Стандартный пункт выдачи не меняет оценку",
                                                                                },
                                                                               {"value": "new_address",
                                                                                "label": "Новый адрес",
                                                                                "risk_points": 3,
                                                                                "trust_cost": 2,
                                                                                "description": "Новый адрес требует дополнительной проверки",
                                                                                },
                                                                               {"value": "no_delivery",
                                                                                "label": "Без доставки",
                                                                                "risk_points": 5,
                                                                                "trust_cost": 4,
                                                                                "description": "Отсутствие поставки уменьшает проверяемый контекст",
                                                                                },
                                                                               ],
                                                                   },
                                                                  ),
                                              "refund": ({"key": "refund_reason",
                                                          "label": "Причина возврата",
                                                          "kind": "select",
                                                          "default": "item_return",
                                                          "options": [{"value": "item_return",
                                                                       "label": "Возврат товара",
                                                                       "risk_points": -2,
                                                                       "trust_cost": -1,
                                                                       "time_cost": 1,
                                                                       "description": "Обычный возврат связан с исходной покупкой",
                                                                       },
                                                                      {"value": "order_cancelled",
                                                                       "label": "Отмена заказа",
                                                                       "risk_points": 0,
                                                                       "description": "Отмена заказа не дает отдельного сигнала",
                                                                       },
                                                                      {"value": "service_dispute",
                                                                       "label": "Спор по услуге",
                                                                       "risk_points": 4,
                                                                       "trust_cost": 3,
                                                                       "description": "Спор по услуге сложнее проверить автоматически",
                                                                       },
                                                                      {"value": "chargeback",
                                                                       "label": "Оспаривание платежа",
                                                                       "risk_points": 7,
                                                                       "trust_cost": 5,
                                                                       "energy_cost": 1,
                                                                       "description": "Оспаривание требует отдельного расследования",
                                                                       },
                                                                      ],
                                                          },
                                                         {"key": "refund_destination",
                                                          "label": "Куда вернуть деньги",
                                                          "kind": "select",
                                                          "default": "original_method",
                                                          "options": [{"value": "original_method",
                                                                       "label": "На исходный способ оплаты",
                                                                       "risk_points": -4,
                                                                       "trust_cost": -3,
                                                                       "description": "Возврат на исходный счет замыкает понятный маршрут",
                                                                       },
                                                                      {"value": "other_card",
                                                                       "label": "На другую карту",
                                                                       "risk_points": 7,
                                                                       "trust_cost": 7,
                                                                       "energy_cost": 1,
                                                                       "description": "Смена получателя разрывает связь с исходной покупкой",
                                                                       },
                                                                      {"value": "digital_wallet",
                                                                       "label": "На электронный кошелек",
                                                                       "risk_points": 10,
                                                                       "trust_cost": 9,
                                                                       "energy_cost": 1,
                                                                       "description": "Возврат в другой канал затрудняет прослеживаемость",
                                                                       },
                                                                      ],
                                                          },
                                                         ),
                                              }


def context_fields_for(card_code: str) -> tuple[dict[str, Any], ...]:
    """Declarative context-field specs that apply to one card code."""
    return tuple(
        deepcopy(CONTEXT_FIELDS[key])
        for key in ACTION_CONTEXT_FIELDS.get(card_code, ())
    )


def action_fields_for(card_code: str) -> tuple[dict[str, Any], ...]:
    """Declarative action-detail field specs for one card code."""
    return deepcopy(ACTION_PARAMETER_SCHEMAS.get(card_code, ()))


def default_context(card_code: str) -> dict[str, Any]:
    return {field["key"]: field["default"] for field in context_fields_for(card_code)}


def default_action_details(card_code: str) -> dict[str, Any]:
    return {field["key"]: field["default"] for field in action_fields_for(card_code)}


def context_value_label(field_key: str, value: Any) -> str:
    field = CONTEXT_FIELDS.get(field_key)
    if field is None:
        return str(value)
    if field["kind"] == "toggle":
        return "Да" if value else "Нет"
    option = next(
        (item for item in field.get("options", []) if item["value"] == value),
        None,
    )
    return option["label"] if option else str(value)


def option_label(fields: Sequence[dict[str, Any]], field_key: str, value: Any) -> str:
    """Label of one option inside a declarative field list."""
    for field in fields:
        if field["key"] != field_key:
            continue
        option = next(
            (item for item in field.get("options", []) if item["value"] == value),
            None,
        )
        return option["label"] if option else str(value)
    return str(value)


def detail_factor_label(card_code: str, field_key: str, value: Any) -> str:
    for field in action_fields_for(card_code):
        if field["key"] != field_key:
            continue
        return f"{field['label']}: {option_label([field], field_key, value)}"
    return f"{field_key}: {value}"
