"""initial_schema

Revision ID: 2988b0ed1f98
Revises: 
Create Date: 2026-08-28 21:29:31.163450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2988b0ed1f98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_cards',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('flow', sa.String(), nullable=False),
    sa.Column('risk_weight', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=False),
    sa.Column('time_cost', sa.Integer(), nullable=False),
    sa.Column('trust_cost', sa.Integer(), nullable=False),
    sa.Column('fee_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_frequency', sa.Integer(), nullable=False),
    sa.Column('requires_card_code', sa.String(), nullable=True),
    sa.Column('parameter_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_action_cards_code_version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_by_user_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=True),
    sa.Column('access_revision', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rounds',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_revision', sa.Integer(), nullable=False),
    sa.Column('game_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_status'), 'rounds', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('session_id_hash', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=100), nullable=True),
    sa.Column('rotated_from_session_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rotated_from_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('participant_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resource_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('last_client_mutation_id', sa.Uuid(), nullable=True),
    sa.Column('payload_hash', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'participant_id', name='uq_scenarios_round_id_participant_id')
    )
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=True),
    sa.Column('round_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=True),
    sa.Column('scenario_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('idempotency_key_hash', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_adjustments',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('admin_user_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('risk_score_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('resource_score_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('game_score_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', name='uq_leaderboard_adjustments_scenario_id')
    )
    op.create_table('scoring_results',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('risk_label', sa.String(), nullable=False),
    sa.Column('stealth_score', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('resource_score', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('game_score', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_version', sa.String(), nullable=False),
    sa.Column('leaderboard_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', name='uq_scoring_results_scenario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_results')
    op.drop_table('leaderboard_adjustments')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_rounds_status'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('action_cards')
    # ### end Alembic commands ###
